FROM mrc.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["Vendas.API/Vendas.API.csproj", "Vendas.API/"]
RUN dotnet restore "Vendas.API/Vendas.API.csproj"
COPY . .
WORKDIR "/src/Vendas.API"
RUN dotnet build "Vendas.API.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "Vendas.API.csproj" -c Release -o /app/publish


FROM base AS final
WORKDIR /app