FROM mrc.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["Estoque.API/Estoque.API.csproj", "Estoque.API/"]
RUN dotnet restore "Estoque.API/Estoque.API.csproj"
COPY . .
WORKDIR "/src/Estoque.API"
RUN dotnet build "Estoque.API.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "Estoque.API.csproj" -c Release -o /app/publish


FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Estoque.API.dll"]